config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :products
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_attached_file :image, 
    styles: { 
      main: "270x357#", 
      medium: "170x224#", 
    }
  validates_attachment :image, :presence => true,
    :content_type => { :content_type => "image/jpeg" },
    :size => { :in => 0..2000.kilobytes }

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout 'admin'
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock, :sale, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_products = Product.order('created_at desc').limit(4)
    @sale_products = Product.where(sale: true).order('created_at desc').limit(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product], html: { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :sale %><br>
    <%= f.check_box :sale %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Sale:</strong>
  <% if @product.sale %>
    SI
  <% else %>
    NO
  <% end %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image.url %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/home/index.html.erb
<div class="row column text-center">
<h2>Nuestros más nuevos productos</h2>
<hr>
</div>

<div class="row small-up-2 large-up-4">

<% @latest_products.each do |product| %>
  <div class="column">
    <%= image_tag product.image.url(:main), class: 'thumbnail' %>
    <h5><%= product.name %></h5>
    <p><%= product.price %></p>
    <a href="#" class="button expanded">Buy</a>
  </div>
<% end %>

</div>

<hr>
<div class="row column">
<div class="callout primary">
<h3>Tambíen podes ver los productos de oferta</h3>
</div>
</div>
<hr>
<div class="row column text-center">
<h2>Productos en oferta!</h2>
<hr>
</div>
<div class="row small-up-2 medium-up-3 large-up-6">

  <% @sale_products.each do |product| %>
    <div class="column">
    <%= image_tag product.image.url(:medium), class: 'thumbnail' %>
    <h5><%= product.name %></h5>
    <p><%= product.price %></p>
    <a href="#" class="button small expanded hollow">Buy</a>
    </div>
  <% end %>

</div>
<hr>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Administracion de E-Commerce</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <h1>Seccion de Administración</h1>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Aplicacion de E-Commerce</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="top-bar">
    <div class="top-bar-left">
    <ul class="menu">
    <li class="menu-text">Marketing Site</li>
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    </ul>
    </div>
    <div class="top-bar-right">
    <ul class="menu">
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
    <li><a href="#">Five</a></li>
    <li><a href="#">Six</a></li>
    </ul>
    </div>
    </div>

    <%= yield %>

    <div class="callout large secondary">
    <div class="row">
    <div class="large-4 columns">
    <h5>Vivamus Hendrerit Arcu Sed Erat Molestie</h5>
    <p>Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed molestie augue sit.</p>
    </div>
    </div>
    <div class="large-3 large-offset-2 columns">
    <ul class="menu vertical">
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
    </ul>
    </div>
    <div class="large-3 columns">
    <ul class="menu vertical">
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
    </ul>
    </div>
    </div>

  </body>
</html>